defaults: 
  - DexterityTaskBinPickPPO



params:
  algo:
    name: dagger_continuous
  # Overwrite rl-games minibatch_size, which is not used for DAgger, but would otherwise cause an AssertionError.
  config:
    minibatch_size: ${....task.env.numEnvs}

  # Build PointNet-like encoders for observations that include pointclouds.
  network:
    name: pointnet_actor_critic


  dagger:
    learning_rate: 0.001
    miniepochs: 10

    teacher:
      checkpoint: ${.....teacher_checkpoint}
      batch_size: 400  # Batch size for (obs, teacher_actions) sampled from teacher dataset
      dataset_capacity: 1e6  # Maximum number of (obs, teacher_actions) that fit in teacher dataset
      action_prob_init: 0.0  # Initial probability of using teacher action
      action_prob_decay: 0.9  # Decay rate of teacher action probability.
